apiVersion: v1
data:
  config.yaml: Li4uCkZFQVRVUkVfVVNFUl9JTklUSUFMSVpFOiB0cnVlCkJST1dTRVJfQVBJX0NBTExTX1hIUl9PTkxZOiBmYWxzZQpTVVBFUl9VU0VSUzoKLSBxdWF5YWRtaW4KRkVBVFVSRV9VU0VSX0NSRUFUSU9OOiBmYWxzZQpTRVJWRVJfSE9TVE5BTUU6IHJlZ2lzdHJ5LmFwcHMudGVzdC1jbHVzdGVyMS5zYW5kYm94MTg1Ny5vcGVudGxjLmNvbQouLi4K
kind: Secret
metadata:
  creationTimestamp: null
  name: config-bundle-secret
